name: Pelican Build
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Build and Publish
      uses: nelsonjchen/gh-pages-pelican-action@master
      working-directory: docs
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        PELICAN_CONFIG_FILE: docs/publishconf.py
